name: Resize Images

on:
  push:
    branches:
      - main

jobs:
  resize_images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python pil.py
